import * as WorkflowNamespace from '../../typings/workflow';

export default class WorkflowBase {
  StartActivity: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '开始',
    name_i18n: {},
    activityType: 'START',
    icon: '&#xe897;',
    allowedTime: null,
    timeoutWarning1: null,
    timeoutWarning2: null,
    timeoutStrategy: 'NOTIFY_HANDLER',
  }

  EndActivity: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '结束',
    name_i18n: {},
    activityType: 'END',
    icon: '&#xe9a7;',
    allowedTime: null,
    timeoutWarning1: null,
    timeoutWarning2: null,
    timeoutStrategy: 'NOTIFY_HANDLER',
  }

  UserActivity: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '用户活动',
    name_i18n: {},
    activityType: 'PARTICIPANT',
    icon: '&#xe935;',
    participant: null,
    submitButtonName: null,
    rejectButtonName: null,
    finishExit: null,
    sheetCode: '',
    assistant: '',
    circulate: '',
    permittedAction: {
      adjustParticipant: false,
      assist: false,
      circulate: false,
      finishInstance: false,
      forward: true,
      reject: false,
      rejectToActivityCode: '',
      rejectToFixded: false,
      rejectToStart: true,
      retrieve: true,
    },
    participantType: 'SINGLE_PARTICIPANT',
    participationModel: 'PARALLEL',
    approveExit: '100%',
    disapproveExit: '1',
    noParticipant: 'TO_ADMIN',
    beforeActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    afterActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    endActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    cancelActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobSubmitted: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobRejected: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    asyncEndJob: null,
    originator: 'DEFAULT',
    perviousParticipate: '',
    participated: '',
    followUpParticipate: '',
    targetActivityCode: null,
    noParticipantNextActivity: 'DEFAULT',
    allowedTime: '',
    timeoutWarning1: '',
    timeoutWarning2: '',
    timeoutStrategy: 'NOTIFY_HANDLER',
    propertyPermissions: [],
    todoDataItem: {dataItemType: 0, summary: [], title: []}
  }

  SysActivity: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '系统活动',
    name_i18n: {},
    activityType: 'SYSTEM_ACTIVITY',
    icon: '&#xe947;',
    bizActions: [],
    finishCondition: null,
    beforeActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    afterActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    endActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    cancelActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobSubmitted: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobRejected: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
  }

  SubWorkflow: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '子流程',
    name_i18n: {},
    activityType: 'SUB_INSTANCE',
    icon: '&#xe9d5;',
    participant: '',
    participantType: 'SINGLE_PARTICIPANT',
    workflowCode: '',
    workflowChooseAction: '',
    sync: true,
    finishStartActivity: false,
    workflowDataMaps: [],
    triggerMappingObj: null,
    beforeActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    afterActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    endActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    cancelActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobSubmitted: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobRejected: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
  }

  Connection: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '连接点',
    name_i18n: {},
    activityType: 'CONNECTION',
    icon: '&#xe914;',
    allowedTime: null,
    timeoutWarning1: null,
    timeoutWarning2: null,
    timeoutStrategy: 'NOTIFY_HANDLER',
    beforeActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    afterActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    endActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    cancelActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    asyncEndJob: null,
    jobSubmitted: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobRejected: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
  }

  Circulate: WorkflowNamespace.Activity = {
    left: 0,
    top: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    right: 0,
    bottom: 0,
    center: 0,
    middle: 0,
    activityCode: '',
    isSelected: false,
    toolTipText: '',
    activityName: '传阅',
    name_i18n: {},
    activityType: 'CIRCULATE',
    icon: '&#xe910;',
    allowedTime: '',
    timeoutWarning1: '',
    timeoutWarning2: '',
    timeoutStrategy: 'NOTIFY_HANDLER',
    beforeActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    afterActivate: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    endActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    cancelActivity: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    asyncEndJob: null,
    jobSubmitted: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    jobRejected: {
      receiver: null,
      content: null,
      cancelParllelActivity: false,
      rejectCancelParllelActivity: true,
      dataDisposals: [],
      bizActions: []
    },
    participantType: 'MULTI_PARTICIPANT'
  }
}
